### ISSUE TITLE
Node exporter metrics from Windows Node are not published to container insights (log analytics workspace)

### ISSUE THREAD

**Issue by gyuvaraj10** [Microsoft/Docker-Provider#1099]
Node exporter metrics from Windows Node are not published to container insights (log analytics workspace)

Steps to Reproduce:
1. Deploy the Windows Node exporter Daemonsets on all the windows nodes
2.  Configure the configmap container-azm-ms-agentconfig as below
     ```
  [prometheus_data_collection_settings.node]
    # Node level scrape endpoint(s). These metrics will be scraped from agent's DaemonSet running in every node in the cluster
    # Any errors related to prometheus scraping can be found in the KubeMonAgentEvents table in the Log Analytics workspace that the cluster is sending data to.

    #Interval specifying how often to scrape for metrics. This is duration of time and can be specified for supporting settings by combining an integer value and time unit as a string value. Valid time units are ns, us (or µs), ms, s, m, h.
    interval = "1m"

    ## Uncomment the following settings with valid string arrays for prometheus scraping

    # An array of urls to scrape metrics from.  (all upper case) will substitute of running Node's IP address
    urls = ["http://$NODE_IP:9182/metrics", "http://10.1.0.223:9182/metrics"]

    #fieldpass = ["metric_to_pass1", "metric_to_pass12"]

    #fielddrop = ["metric_to_drop"]
```

Expected Result:
Log analytics workspace should have the metrics logged with the Computer name being windows node name

Actual Result:
Log analytics workspace should have the metrics logged with the Computer name being linux (systempool) node name.

**Comment by vdiec** [comment]
@jatakiajanvi12 please take a look

**Comment by gyuvaraj10** [comment]
please let me know if there is an update on it

**Comment by vdiec** [comment]
@gyuvaraj10 we are now recommending Azure Monitor managed service for Prometheus for your metrics https://learn.microsoft.com/en-Us/azure/azure-monitor/containers/prometheus-metrics-enable?tabs=azure-portal#enable-windows-metrics-collection . Please let us know if you have questions or concerns!
