### ISSUE TITLE
Allow collecting logs only from included namespaces

### ISSUE THREAD

**Issue by theadzik** [Microsoft/Docker-Provider#1103]
In the [container-azm-ms-agentconfig ConfigMap](https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml) it is only allowed to exclude_namespaces:

```
[log_collection_settings]
       [log_collection_settings.stdout]
          enabled = true
          exclude_namespaces = ["kube-system","gatekeeper-system"]
```

It would be helpful, especially for dynamic clusters where namespaces change often, to have possibility to collect logs only from included namespaces:

```
[log_collection_settings]
       [log_collection_settings.stdout]
          enabled = true
          include_namespaces = ["my-app-namespace"]
```

If we are interested in logs from only one specific namespace we need to keep updating `exclude_namespaces` every time a new namespace is added.

**Comment by vdiec** [comment]
@theadzik thank you for the feedback! We will add this to our backlog and update this thread once we address this (most likely early next year)

**Comment by ganga1980** [comment]
Hi, @theadzik , thanks for the feedback. We have backlog work item to implement the feedback. Tentative ETA is around Feb 2024.

**Comment by theadzik** [comment]
@ganga1980 Hi, any updates on this? :)

**Comment by theadzik** [comment]
@vdiec Any updates? :)
