### ISSUE TITLE
Add ability to use existing secret to helm chart

### ISSUE THREAD

**Issue by djryanj** [Microsoft/Docker-Provider#1117]
Storing something like the values for the Log Analytics workspace ID and key in an external Key Management System (like Azure Key Vault) and injecting them into releases using something like the External Secrets Operator (ESO) is a better security posture than passing those values via the command line. This is especially relevant when deploying using GitOps; if not using a KMS with ESO or something like it, it requires you to have the secret values in the git repo which is against best practices.

It is common in charts to see the use of something like `existingSecret` (see: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L4037 and https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/secret.yaml for an example) which permits exactly this. Obviously the secret has to be in the correct format, but that is relatively trivial all things considered, and increases the security of the deployment by putting secrets where they belong.

**Comment by ganga1980** [comment]
Hi, @djryanj - For both AKS and Azure Arc Enabled Kubernetes, passing of the workspace key is not required for both Managed Identity and legacy auth.  In case of the Managed Identity auth, there is no dependency on the workspace key as we use the Managed Identity for auth - https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-authentication?tabs=portal-azure-monitor and incase of the legacy auth, workspace key automatically fetched. Can you please more details about your scenario and how you are using Container Insights?

**Comment by djryanj** [comment]
Hi @ganga1980 thanks for the reply.

My workload is in a hybrid Kubernetes cluster that's using federated credentials (non-Arc). The documents on hybrid clusters (https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-hybrid-setup) don't mention using federated credentials, and explicitly call out finding and providing the workspace key to the chart.

For what it's worth, my cluster is running in Azure VMs and the identity in question is a user-managed identity; Kubernetes is using that with federated credentials via AZWI for other things (e.g., I have `kube-prometheus` installed with remote write to an Azure Monitor workspace using workload identity even though that's not a documented scenario for a hybrid cluster like mine).
