### ISSUE TITLE
hidden properties in configmap

### ISSUE THREAD

**Issue by ripenedcat** [Microsoft/Docker-Provider#1318]
There are some hidden properties which could optimize the agent to handle large large scale pods scenario, like 60k+ pods. 
An example properties is POD_CHUNK_SIZE. 
Post this just want to have a double check if we are going to include those properties into the configmap here https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml?

Thanks.

**Comment by ganga1980** [comment]
Thanks for the feedback. Sure, we will expose to this  config map.
