### ISSUE TITLE
ContainerInventory table continuously populated with duplicated entries every few seconds, costing a lot

### ISSUE THREAD

**Issue by DaveAurionix** [microsoft/Docker-Provider#172]
# Issue

Hi, we have two clusters running Container Insights and are paying hundreds of pounds each month for the Log Analytics bill.  It has become the most expensive part of our Azure bill.  Looking into this, the ContainerInventory table is flooded with many messages a second.  On the surface, OMS agent appears to be sending the same messages many times.  This seems to be happening on both clusters.

Please could you let us know how we can reduce the volume of data that OMS agent sends to Log Analytics for this table?

# To reproduce

The OMS version in use is `microsoft/oms:ciprod10162018-2`.

Example:
The following Log Analytics query shows the ContainerInventory table contains almost 3 times as much data as any other table.
```
Usage
| where IsBillable = true
| summarize Quantity=sum(Quantity) by SourceSystem, DataType, Solution
| order by Quantity desc
```

The result shows the top row has a SourceSystem of `OMS`, a DataType of `ContainerInventory` and a Solution of `ContainerInsights`.  We're ingesting 8GB per week on our test environment just to that table.

Running the following query on that table helps show the suspected duplicate entries.  Note that kube-dns was picked as a common example but the problem occurs for every container.
```
ContainerInventory
| where TimeGenerated > ago(1d) and ContainerHostname startswith "kube-dns"
| order by TimeGenerated desc
```

The result shows lots of rows with unique values in the `TimeGenerated [UTC]` column, but duplicate values in all other columns.  A good indicator is to check the values of the `CreatedTime [UTC]` and `StartedTime [UTC]` columns at the end - they seem to be exactly the same for many different values of TimeGenerated.  This implies that the same Kubernetes events are being reported by the OMS agent to Log Analytics many times over.

Please could you let us know how we can reduce the volume of data that OMS agent sends to Log Analytics for this ContainerInventory table as the cost impact is currently a problem?

# Background

We are deploying the OMS agent using the addon in the ARM template:
```json
"addonProfiles": {
  "omsagent": {
    "enabled": true,
    "config": {
      "logAnalyticsWorkspaceResourceID": "[parameters('logAnalyticsWorkspaceResourceId')]"
    }
  }
}
```

We have five OMS pods running as a result (there are currently four nodes in the test cluster this is taken from):
```
omsagent-d9cvb                          1/1     Running   1          20h
omsagent-drz85                          1/1     Running   3          7d
omsagent-p6jts                          1/1     Running   4          7d
omsagent-rs-ccf8b9699-9976m             1/1     Running   0          2d
omsagent-swwpq                          1/1     Running   4          7d
```

Thanks!

**Comment by DaveAurionix** [comment]
To clarify: the clusters are both Azure Kubernetes Service clusters.  The high Log Analytics cost seems to have really become a problem in the last 5-8 weeks (i.e. sometime during the last Azure billing invoice period).

**Comment by DaveAurionix** [comment]
Our billing history for Log Analytics data ingestion shows this trend:

resource title "data ingestion" - resource guid e5626349-2f1f-4563-babc-dc9219884716
13/11-12/12 - £275.46
13/10-12/11 - £183.60

old resource title "LA data ingestion" - same resource guid
13/09-12/10 - £100.36
13/08-12/09 - £116.49
13/07-12/08 - £117.07

Under the old resource title the costs looked stable albeit very high for background logging, however under the new resource title the costs are escalating quickly and this is now very concerning.

We urgently need to discuss a solution to stop the OMS docker agent feeding the same Kubernetes events into the ContainerInventory table repeatedly every few seconds.  In our view this is a bug which is critical due to the sudden cost implication, presumably made more visible after a change in the billing approach.

The next highest used table by far is the Perf table.  Again, we need a means to reduce the frequency that perf counters are logged to Log Analytics through the OMS Docker agent.

For reference, in the last 30 days on our test environment alone we have ingested:
14GB of repeated ContainerInventory records.
8GB of Perf records.
5GB of ContainerLog records.

The first two tables above we believe are under Microsoft's control and the first table at least is impacted by this bug.  We're not at all keen on paying for these.  £300 per month to record lots of duplicate records every few seconds is not feasible.

If this repository is the wrong place to file this issue, please do put me right.

Urgent assistance is requested and would be appreciated due to the perception of uncontrollable costs.

I understand that we can cap the data ingested each day through an option in Azure Portal but this would discard useful data as the ContainerInventory ingestion bug would consume the capped allowance.

**Comment by DaveAurionix** [comment]
Have made some progress ... it looks as if there are two causes:
1. Regular cronjobs in Kubernetes cause large numbers of events in the ContainerInventory table as the current version of Kubernetes seems to try to start several containers for a job at the same time, which is why there are lots of identical-looking rows in the table.  We're reacting to this by moving frequent cronjobs into continuously-running containers instead.
2. The state of every container is logged once per minute even if it hasn't changed.  In environments running large numbers of pods (microservices) this quicky becomes a lot of unnecessary data sent through to Log Analytics.  I'm not yet clear whether this is Kubernetes or OMS Docker Agent doing this.  If it is the OMS agent then we need to control this interval (to increase it).  **Please could you share how we can configure this, or confirm that this is outside of the OMS Agent's control?**

**Comment by DaveAurionix** [comment]
After moving away from cronjobs on Kubernetes with Container Insights installed, the next highest causes of data ingestion are the ContainerInventory and Perf metrics that are written to Log Analytics once per minute.  For us means about 1GB per day per environment.  The configuration for this interval appears to be in the omsagent-rs-config ConfigMap in Kubernetes.  This ConfigMap appears to be written every time the omsagent-rs pod starts.  Presumably this config is being retrieved from the OMS workspace?

Please could you share how we can reconfigure the frequency of collection, e.g. to every 3 mins?

**Comment by bpummill1** [comment]
@DaveAurionix did you ever figure out how to update the frequency of collection?
