### ISSUE TITLE
Missing information in syslog warning: Container image name (%s) is improperly formed and could not be parsed in SetRepositoryImageTag

### ISSUE THREAD

**Issue by adiian** [microsoft/Docker-Provider#353]
It appears that when an image has a <none> tag, a warning is logged in InventoryQuery::SetImageRepositoryImageTag at syslog(LOG_WARNING, "Container image name (%s) is improperly formed and could not be parsed in SetRepositoryImageTag", properties.c_str());

The syslog message is does not contain the image name: "Container image name () is improperly...". All the docker images are having names, so the name is available and should be displayed in the message.

**Comment by achevalet** [comment]
Same here... note that this malformed message also generates noise (and cost if it is sent to Log Analytics) in syslog every minute:

 ```
Mar 24 19:05:49 myhost Container_ImageInventory[9123]: Container image name () is improperly formed and could not be parsed in SetRepositoryImageTag
Mar 24 19:06:49 myhost Container_ImageInventory[9123]: Container image name () is improperly formed and could not be parsed in SetRepositoryImageTag
Mar 24 19:07:49 myhost Container_ImageInventory[9123]: Container image name () is improperly formed and could not be parsed in SetRepositoryImageTag
Mar 24 19:08:49 myhost Container_ImageInventory[9123]: Container image name () is improperly formed and could not be parsed in SetRepositoryImageTag
Mar 24 19:09:49 myhost Container_ImageInventory[9123]: Container image name () is improperly formed and could not be parsed in SetRepositoryImageTag
```

**Comment by Klaas-** [comment]
I am guessing this was closed without a resolution, I still see this as log spam with current log analytics agent
