### ISSUE TITLE
Some Kubernetes events are not being forwarded to OMS

### ISSUE THREAD

**Issue by dave-read** [Microsoft/Docker-Provider#38]
We've seen cases where Kubernetes life-cycle events for Pods (e.g. Killed) could be seen in output from `kubectl get events`, but did not show up in OMS log analytics.  

It looks like there may be an issue with the way **_previously seen events_** are being tracked.  In [in_kube_events.rb](https://github.com/Microsoft/Docker-Provider/blob/master/source/code/plugin/in_kube_events.rb#L60) ,the `uuid` from the event is used to track which events have already been seen.  If the `uuid` is already in the `KubeEventsStateFile`, then the event is skipped, otherwise it's routed to the registered outputs.  

The issue is that for some events (e.g. Pod events), the `uuid` does not change when the event occurs again for the same Pod.  Instead the `count` and `lastTimestamp` property values are updated.

Here's an example of a Pod where there were there were multiple `Killing` events.  In this case the `uuid` is `fb90522d-a65a-11e7-bafb-000d3a36fbf1`.  The first event has `count:970`

```
{
      "metadata": {
        "name": "liveness-exec.14e9557aa4eccb1d",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/events/liveness-exec.14e9557aa4eccb1d",
        "uid": "fb90522d-a65a-11e7-bafb-000d3a36fbf1",
        "resourceVersion": "3815919",
        "creationTimestamp": "2017-10-01T03:45:35Z"
      },
      "involvedObject": {
        "kind": "Pod",
        "namespace": "default",
        "name": "liveness-exec",
        "uid": "9089e7fd-a3be-11e7-9da0-000d3a36fbf1",
        "apiVersion": "v1",
        "resourceVersion": "3302183",
        "fieldPath": "spec.containers{liveness}"
      },
      "reason": "Killing",
      "message": "(events with common reason combined)",
      "source": {
        "component": "kubelet",
        "host": "k8s-agentpool1-39011252-2"
      },
      "firstTimestamp": "2017-10-01T03:45:35Z",
      "lastTimestamp": "2017-10-05T00:37:45Z",
      "count": 970,
      "type": "Normal"
}
```
A subsequent `Killing` event for the same Pod (`count:971`) followed but would have been skipped because it has the same `uuid` as the first event.

```
  {
      "metadata": {
        "name": "liveness-exec.14e9557aa4eccb1d",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/events/liveness-exec.14e9557aa4eccb1d",
        "uid": "fb90522d-a65a-11e7-bafb-000d3a36fbf1",
        "resourceVersion": "3816442",
        "creationTimestamp": "2017-10-01T03:45:35Z"
      },
      "involvedObject": {
        "kind": "Pod",
        "namespace": "default",
        "name": "liveness-exec",
        "uid": "9089e7fd-a3be-11e7-9da0-000d3a36fbf1",
        "apiVersion": "v1",
        "resourceVersion": "3302183",
        "fieldPath": "spec.containers{liveness}"
      },
      "reason": "Killing",
      "message": "(events with common reason combined)",
      "source": {
        "component": "kubelet",
        "host": "k8s-agentpool1-39011252-2"
      },
      "firstTimestamp": "2017-10-01T03:45:35Z",
      "lastTimestamp": "2017-10-05T00:43:30Z",
      "count": 971,
      "type": "Normal"
    }

```
We've tried an experiment by concatenating the `count` property with the `uuid` property to construct  the `eventId` for tracking seen events.   Another option would have been to use the `lastTimestamp` property.  That seems to resolve the issue of events being skipped.  However, we also see periods of time where events are not forwarded, but that seems unrelated to this.

**Comment by dave-read** [comment]
Here's the [experiment](https://github.com/dave-read/Docker-Provider/commit/3616efa6230909ddb67e6d911921277999471e01)  we did to add the count property to the eventId.   It also adds the first and last seen time-stamps along with the count property to the event.    That make the event values in Log Analytics easier to interpret, but there may be issues with adding new properties.

**Comment by samisms** [comment]
@dave-read took your changes as is. Getting all events now. Feel free to send out a PR if you want to make any further changes. Any contribution is highly welcome :) Thanks.
