### ISSUE TITLE
[Feature Request] Ability to set PriorityClass for OMSAgent in AKS

### ISSUE THREAD

**Issue by davelosert** [microsoft/Docker-Provider#391]
I am not sure if this is the correct repository to open this issue, but:

**It would be great if it was possible to somehow configure a priority-class for the `omsagent` within an AKS-Cluster.**

Currently, that does not seem possible - or at least I could find no documentation whatsoever about it.

In our scenario, we want to give the cluster monitoring a somewhat higher priority than most of the other services - so that in case of an error, we won't be flying blind.

The only workaround I can think of is to use a `global default` class - however that is not really feasible as there might be other, unimportant pods without a `PriorityClass` within the cluster that might suddenly be ranked way higher than they should be.

Is such a feature possible?

**Comment by daweim0** [comment]
@davelosert does setting omsagent.priority solve your problem? [docs here](https://github.com/Michael-Sinz/Docker-Provider/blob/ci_dev/charts/azuremonitor-containers/README.md#configuration)  (sorry for bringing a year-old issue back to life, I'm doing some cleanup)

We don't support changing the priority class in managed deployments (onboarding a cluster through the azure portal or cli). However, that runs omsagent pods with the system-node-critical priority class, which should be high enough?

**Comment by davelosert** [comment]
@daweim0 : Thanks for your response and the tip.

However, we switched to another monitoring solution so unfortunately I can not try this out anymore.
Mabye there is someone else who is experiencing the same problem might be able to try and give you a feedback?
