### ISSUE TITLE
enable-monitoring.sh fails if az output format not set to json

### ISSUE THREAD

**Issue by jamurtag** [microsoft/Docker-Provider#409]
The bash script to [enable monitoring for Arc clusters](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-enable-arc-enabled-clusters#enable-using-bash-script) fails if the output format is not json.

An example when output format is set to `table`:

```bash
$ bash enable-monitoring.sh --resource-id $azureArcClusterResourceId --kube-context $kubeContext --workspace-id $logAnalyticsWorkspaceResourceId
...
validating cluster identity
cluster identity type: result -------------- systemassigned
-e only supported cluster identity is systemassigned for Azure ARC K8s cluster type
```

The az command formatting only works for single line output.

In addition, a script does not satisfy our automation workflows, it would be useful to see RM/Terraform code to configure the workspace then instructions to implement the Helm chart natively.

**Comment by ganga1980** [comment]
Hi, @jamurtag,  We are working on moving to extension model to enable monitoring for Arc K8s cluster(s) and with extension model, there is simple integrated CLI command and also can be enabled with RM & Policy etc. This script will be removed at that time. We are targetting extension model to release in couple of weeks.

**Comment by nyuen** [comment]
@ganga1980 Should we close the issue following the merge #513 ?
