### ISSUE TITLE
wrong version for "microsoft/oms:win-ciprod10272020"?

### ISSUE THREAD

**Issue by AbelHu** [microsoft/Docker-Provider#472]
https://github.com/microsoft/Docker-Provider/blob/ci_prod/ReleaseNotes.md#version-microsoftomswin-ciprod10272020-version-mcrmicrosoftcomazuremonitorcontainerinsightsciprodwin-ciprod10052020-windows
```
Version microsoft/oms:win-ciprod10272020 Version mcr.microsoft.com/azuremonitor/containerinsights/ciprod:win-ciprod10052020 (windows)
```

Should it be "Version microsoft/oms:win-ciprod10272020 Version mcr.microsoft.com/azuremonitor/containerinsights/ciprod:win-ciprod10272020"?
@vishiy

**Comment by daweim0** [comment]
Thanks for pointing that out, looks like it was fixed and this issue was never closed.
