### ISSUE TITLE
Fix doc link

### ISSUE THREAD

**Issue by dcbrown16** [microsoft/Docker-Provider#475]
Where it says "Create and use a parameters file as a JSON" on the following page, the linked doc is a review page, not the public docs.
https://github.com/microsoft/Docker-Provider/tree/ci_dev/alerts/recommended_alerts_ARM

It links to:
https://review.docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files
It should link to:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files

**Comment by daweim0** [comment]
Thank you for pointing this out, finally [fixed](https://github.com/microsoft/Docker-Provider/pull/570))
