### ISSUE TITLE
Issue with azuremonitor-containers helm chart

### ISSUE THREAD

**Issue by sfaisalshah** [microsoft/Docker-Provider#479]
Hi guys,

I am getting below error when I try to install azuremonitor-containers helm chart in arc enabled k8 v1.16.

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "AzureClusterIdentityRequest" in version "clusterconfig.azure.com/v1beta1"`

It looks like it does not support k8 version 1.16. Could you please help with this ? Thanks.

**Comment by vishiy** [comment]
@ganga1980 - CRD is failing.

**Comment by vishiy** [comment]
@saaror @joby-thomas

**Comment by ganga1980** [comment]
Hi, @sfaisalshah, based on the discussion @anagg929 from Arc K8s team, looks like AzureClusterIdentityRequest might got deleted accidently. without this, Arc cluster will not function itself.  Is your Arc cluster working?

**Comment by saaror** [comment]
@sfaisalshah Can you respond to @ganga1980 question? Were you able to resolve this issue? We are closing it. Please open it if the issue still persists.
