### ISSUE TITLE
oms agent stopped working

### ISSUE THREAD

**Issue by alexinthesky** [microsoft/Docker-Provider#552]
oms agent stopped collecting prometheus metrics with log:
2021-04-20T02:17:49Z E! [inputs.prometheus] Unable to watch resources: Get "https://XXXXXXXXXXXX.hcp.westeurope.azmk8s.io:443/api/v1/pods?watch=true": context canceled
2021-04-20T02:17:49Z E! [telegraf] Error running agent: input plugins recorded 1 errors
****************End Telegraf Run in Test Mode**************************
starting fluent-bit and setting telegraf conf file for replicaset
nodename: aks-main-38921269-vmss000000
replacing nodename in telegraf config
File Doesnt Exist. Creating file...
Fluent Bit v1.6.8
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Telegraf 1.18.0 (git: HEAD ac5c7f6a)
2021-04-20T02:17:49Z I! Starting Telegraf 1.18.0
td-agent-bit 1.6.8
stopping rsyslog...
 * Stopping enhanced syslogd rsyslogd
   ...done.
getting rsyslog status...
 * rsyslogd is not running

image tag: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod03262021

we had to manually restart the pod to see prom metrics being collected again

**Comment by rashmichandrashekar** [comment]
@alexinthesky - Did you have to restart the replicaset pod to start seeing the metrics again?

**Comment by alexinthesky** [comment]
Hi,
1. yes I had to kill the '-rs' pod and set it start new to get themetricscollected again
2. I installed the oms agent together with the aks cluster using terraform omsagent block https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#oms_agent

**Comment by rashmichandrashekar** [comment]
Thanks @alexinthesky 
Do you happen to have the full logs from the previous run?

**Comment by alexinthesky** [comment]
nope we don't, as omsagnetconfig by default doesn't collect them in the kube-system namespace

**Comment by rashmichandrashekar** [comment]
@alexinthesky - This is actually a feature where we test out the settings that we are applying and only if it succeeds we make it the actual configuration to scrape metrics.
In this case, looks like there was a transient issue because of which the api server was not reachable and hence the config swapping failed.

**Comment by rashmichandrashekar** [comment]
@alexinthesky - We have a fix for this issue that will be rolling out soon. Do you still see this issue?
