### ISSUE TITLE
Does OMS Agent log individual container cpu/mem usage? 

### ISSUE THREAD

**Issue by adamcarter81** [microsoft/Docker-Provider#555]
I have a bunch of Grafana dashboards showing graphs for container_cpu_usage_seconds_total and container_memory_usage_bytes filtered by our applications - I've had a look and I'm exporting the Prometheus data into Log Anayltics, but I don't think the OMS agent exports any container_* stats?

I am trying to create a metric chart on a dashboard which shows container utilisation - is this data retrievable from Container Insights? I can't seem to find anything at the container level, only node level

Thanks

**Comment by daweim0** [comment]
Hi @adamcarter81, sorry for the late response
We don't collect container level cpu and memory metrics out of the box. You could either use a log query to get the data (log analytics). Another option could be to use the [cpuExceededPercentage and memoryRssExceededPercentage metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-metric-alerts). By default they are only sent if CPU or memory usage exceeds 95%, but the threshold is configurable via configmap.
