### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by MasterKolka** [microsoft/Docker-Provider#624]
Hello,

Is there any way to reduce omsagent memory consumption in the kubernetes cluster? Just for 2 nodes it runs 3 instances of omsagent (1 daemon set - 2 instances, 1 replica set - 1 instance) and each instance uses 300mb of ram. This is the most demanding service in my cluster and it is just a monitoring tool.

**Comment by MasterKolka** [comment]
Still waiting for a reply

**Comment by MasterKolka** [comment]
Still waiting for a reply

**Comment by vishiy** [comment]
@MasterKolka - are you collecting logs ? how much in each node ? since when did the mem usage go up to 300mb/instance ?

**Comment by MasterKolka** [comment]
@vishiy For empty cluster it looks like that - more than 200mb instance
![image](https://user-images.githubusercontent.com/29628534/133041011-3c59737c-4c72-4b39-abdc-c264871ce248.png)

4 services are deployed, 2 instances each, workload is almost 0%
![image](https://user-images.githubusercontent.com/29628534/133041436-64a78bc9-23fd-4ed4-8c77-9b9a6140ebda.png)

**Comment by MasterKolka** [comment]
ConfigMap is:

log-data-collection-settings: |-
    [log_collection_settings]
       [log_collection_settings.stdout]
          enabled = true
          exclude_namespaces = ["kube-system", "calico-system", "gatekeeper-system", "kube-node-lease", "kube-public", "tigera-operator", "default"]

       [log_collection_settings.stderr]
          enabled = true
          exclude_namespaces = ["kube-system", "calico-system", "gatekeeper-system", "kube-node-lease", "kube-public", "tigera-operator", "default"]

       [log_collection_settings.env_var]
          enabled = false
       [log_collection_settings.enrich_container_logs]
          enabled = false
       [log_collection_settings.collect_all_kube_events]
          enabled = false

  metric_collection_settings: |-
    [metric_collection_settings.collect_kube_system_pv_metrics]
      enabled = false

  integrations: |-
    [integrations.azure_network_policy_manager]
        collect_basic_metrics = false
        collect_advanced_metrics = false

**Comment by vishiy** [comment]
@MasterKolka when you say empty cluster it’s still collecting metrics and logs. How many pods and containers you have in there? Also is this a recent issue that you are seeing? I agree 300meg is not ideal.

**Comment by MasterKolka** [comment]
@vishiy P.P.S. For which reasons both Daemon-Sets and Replica-Sets of the same container are used?

**Comment by MasterKolka** [comment]
Still waiting for a reply

**Comment by MasterKolka** [comment]
Still waiting for a reply

**Comment by MasterKolka** [comment]
Still waiting for a reply

**Comment by MasterKolka** [comment]
@austonli 
> it seems like you have a high number of pods
All these pods are **default**. Just a fresh kubernetes cluster in Azure. Without any other installations. Without dashboard, with kubenet, Calico network plugin and Azure policies enabled.

Fresh screenshot with the new configuration with the omsagent-prometeus which are making things worse.
![image](https://user-images.githubusercontent.com/29628534/139660353-84fa6691-ea48-4101-a4e8-0ce8b21c78e2.png)

**Comment by MasterKolka** [comment]
Up

**Comment by MasterKolka** [comment]
Up

**Comment by vishiy** [comment]
@MasterKolka - Can you please file a support ticket? That will help us track this and reduce the default.

**Comment by MasterKolka** [comment]
@vishiy How it could help? You don't have an opportunity to create an AKS cluster in Azure?

**Comment by vishiy** [comment]
@MasterKolka - For issues like this, we dont create a task in product team's board/backlog, as it will take long time to look. Also, we would need cluster information, subscription information to compare against, which we cannot ask here as its public. If you create a support request, specifying this issue # in github, and also your cluster information, it will be a lot faster, as support ticket cannot be closed until investigated. Does that make sense ? Sorry for the inconvenience. Please let me know once you were able to do that and i can close this one.

**Comment by MasterKolka** [comment]
@vishiy Any subscription, any region, any cluster in Azure. Why can't you just create a new AKS cluster in Azure and check? How it could help if I do this? I don't understand this position.
And I'm going to prevent this issue being closed until this will be fixed.

**Comment by austonli** [comment]
Hi @MasterKolka I understand wanting to keep this issue active until you're able to reach a resolution for this situation.

If you are unable to open a support ticket, then can you please reach out to us at askcoin@microsoft.com with the requested details that @vishiy mentioned above? Once we get the supplied information, it will be much easier for us to investigate. Unfortunately, from a public GitHub issue standpoint there is very little we can do for you until then.

**Comment by MasterKolka** [comment]
@austonli Could you make a proper support plan for free for my MSDN Azure subscription to be able to create a support request? There is very little I can do for you until then.
Why is it so problematic for devs to create any empty AKS cluster in Azure?

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by EderRoger** [comment]
Are there any updates? I'm having the same issues in a brand new cluster.

**Comment by ganga1980** [comment]
Hi, @EderRoger , @MasterKolka , can you please share your cluster configuration in terms of the VM SKU, k8s version and workload info- number of pods/containers etc.  along with the  AKS cluster name to understand what contributing this memory usage?

**Comment by robs** [comment]
VM SKU, k8s version seem irrelevant, even the windows builds use a similar amount of memory.

@ganga1980 Do you have an AKS cluster where the OMS agents aren't using 250-300MB?

If you could share your VM SKU and k8s version that would be great :)
