### ISSUE TITLE
Metrics from insights/containers & insights/pods are no longer available

### ISSUE THREAD

**Issue by arabelaa** [microsoft/Docker-Provider#645]
I am unable to see metrics from `insights/containers` & `insights/pods` namespaces in the Metrics explorer inside my AKS cluster.
We are using `mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod08052021` image version.

In the past I was able to see metrics and I was using `oomKilledContainerCount`. 
Looking over the release notes I didn't see specific changes targeting this area.

Thanks in advance.

**Comment by vishiy** [comment]
@arabelaa please open support ticket as we need more information to troubleshoot this issue.

**Comment by arabelaa** [comment]
Opened `2109170050002639` support request.

**Comment by vishiy** [comment]
@arabelaa thanks. i will close this.
