### ISSUE TITLE
Aggregation Type/Aggregation Granularity - Not polutating in Portal page

### ISSUE THREAD

**Issue by kalirajann** [microsoft/Docker-Provider#650]
Aggregation Type/Aggregation Granularity are not populating in portal page & emails are not triggering. But, I see values in export template. 

Alerts were created using SPN account and am trying to see through my enterprise subscription. I guess that I am missing few access or restriction in my organization level, Kindly let me know whether any additional RBAC at Cluster level

**Comment by vishiy** [comment]
@kalirajann - please open support ticket to address your issues. Not sure what you mean by agg type/agg gran not populating, in which part of the azure portal ? please open support ticket, and i will close this.
