### ISSUE TITLE
Update Telegraf to solve Prometheus: reading text format failed

### ISSUE THREAD

**Issue by adamcarter81** [microsoft/Docker-Provider#680]
I raised an issue here: https://github.com/oliver006/redis_exporter/issues/573

Which looks to be caused by: Input.prometheus plugin unable to parse #HELP comment. https://github.com/influxdata/telegraf/issues/8366
https://github.com/influxdata/telegraf/pull/8545

**Comment by vishiy** [comment]
@adamcarter81 - Not sure what exactly you are referring to here. Below is from my quick test.
telegraf version : 1.18.0  ----> (built off of commit - ac5c7f6a)


![image](https://user-images.githubusercontent.com/10353076/139596676-a35929b5-6942-4a55-9ddd-22041323276f.png)

![image](https://user-images.githubusercontent.com/10353076/139596689-40df35ea-79c4-4eae-943c-713326dd7ac8.png)


Please ensure `metric_version = 2`, as all the schema changes are in v2 that we introduced some time back. Please let us know if you need any help.

**Comment by vishiy** [comment]
closing.

**Comment by adamcarter81** [comment]
Hi @vishiy - thanks for the reply. Where do I set metric_version = 2?
The issue I have is the redis stats from () are not being processed by OMS - the log when scraping the redis exporter is:

`2021-11-09T13:29:00Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://15.0.0.62:15020/stats/prometheus: reading text format failed: text format parsing error in line 699: invalid metric name`

So no redis stats ever get uploaded to Azure, but Prometheus does scrape them ok, I can query them there and see them just fine. My troubleshooting lead me to believe it was an issue in Telegraaf, but this might not be right

Thanks

**Comment by vishiy** [comment]
@adamcarter81 we set it for you automatically. Can you please open a support ticket if u need more help?

**Comment by adamcarter81** [comment]
@vishiy thanks - with who? A Microsoft support ticket?

**Comment by vishiy** [comment]
@adamcarter81 thats correct. Thank you.
