### ISSUE TITLE
Disabling stdout without ConfigMap

### ISSUE THREAD

**Issue by dmo2000** [microsoft/Docker-Provider#683]
Hello,

I am running container insights in a machine that do not have Kubernetes and I want to disable sending logs from stdout stream.

In the documentation (https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config), the only way to do that is by using Kubernetes ConfigMap. As I do not have kubernetes installed, I tried to configure this by setting the environment variable AZMON_LOG_EXCLUSION_REGEX_PATTERN=stdout (reference in some files at /build/windows/installer/conf/), but had no success.

I also tried to write a settings file at /etc/config/settings/log-data-collection-settings, but had no success.

Is there any way that I can disable sending stdout logs to azure workspace?

**Comment by vishiy** [comment]
@dmo2000 - Azure monitor container insights is not supported to be run outside Kubernetes environment. Can you please clarify what & how you you are running this, please ? Are you referring to 'container monitoring solution' ?
