### ISSUE TITLE
Divergence between ARM templates and Portal for K8s alarms

### ISSUE THREAD

**Issue by rtrindvg** [microsoft/Docker-Provider#690]
I am in the process of implementing the alarms based on the ARM templates. Comparing the alarms created via the template, it seems the metrics chosen and thresholds are different than what the portal creates for the corresponding alarms in the "Recommended alerts (Preview)" pane.

Maybe it is not wrong, but I would like to understand why the difference.

Examples:
Alarm on the portal: "(New) Container CPU %"
Description: "Average CPU percent is greater than the configured threshold (default is 95%)"
Metric used on the portal: cpuThresholdExceeded > 0
Metric used on the ARM template: cpuExceededPercentage > 95

Alarm on the portal: "(New) Container working set  memory %"
Description: "Average working set memory percent is greater the configured threshold (default is 95%)"
Metric used on the portal: memoryworkingsetthresholdviolated > 0
Metric used on the ARM template: memoryWorkingSetExceededPercentage > 95

**Comment by vishiy** [comment]
@rtrindvg - They are 2 different metrics. We introduced the *violated/*exceeded metrics earlier this year. Portal has been updated to use the latest, whereas templates have not been updated since we introduced this new metric. We will update the templates. Thanks for reporting.

**Comment by vishiy** [comment]
@rtrindvg - I have created an issue on the team's board for this and we will update the templates in Jan, so this can be auto-closed.
