### ISSUE TITLE
OMS Agent Win kube-system100%+ CPU Usage

### ISSUE THREAD

**Issue by SJBarden** [microsoft/Docker-Provider#691]
Been experiencing this issue for some time, and not just on one client. 
Running Sitecore Containers in Azure.
Advised after raising a support request that advise from MS Support was:

_**"After discussed with our container product team, seems it’s an known issue for windows containerd. And now the windows contained is an opensource and maintained by community, which means any issue regarding contained issue, we have to raise an issue to the community for the tracking. Thanks for your understanding!"**_

So hence I am raising issue here for help.  There are obviously issues with restarts as you can see in the image, though that it seems that it is being investigated separately by MS.

So any assistance on this would be appreciated.
![OMS Agent Win](https://user-images.githubusercontent.com/71366162/144157619-aa24acf9-528a-477e-990a-d450727291f1.png)

**Comment by vishiy** [comment]
@SJBarden - This is not containerd repo. Did you intend to report to containerd ? 
For monitoring/oms pod, we are looking into this issue that happens sporadically in some of the clusters.
