### ISSUE TITLE
OSM Agent high memory usage

### ISSUE THREAD

**Issue by MrImpossibru** [microsoft/Docker-Provider#694]
Hello,

Is there any way to reduce omsagent memory consumption in the kubernetes cluster? Just for 2 nodes it runs 3 instances of omsagent (1 daemon set - 2 instances, 1 replica set - 1 instance) and each instance uses 300mb of ram. This is the most demanding service in my cluster and it is just a monitoring tool.

Reopening because of last Issue was closed automatically.
https://github.com/microsoft/Docker-Provider/issues/624

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by MasterKolka** [comment]
up

**Comment by EderRoger** [comment]
Are there any updates? I'm having the same issues in a brand new cluster.

**Comment by MasterKolka** [comment]
Looks like no. I have to write anything every 7 days here just to prevent this issue to be closed automatically.
And also it looks like nobody cares about this. For a half of a year this issue is opened already.

**Comment by MasterKolka** [comment]
@ganga1980 I wrote all info there - https://github.com/microsoft/Docker-Provider/issues/624
As for now, it is reproduceable on any new empty cluster. 300mb of ram per omsagent instance + 150mb of ram per omsagent-prometeus instance. Which takes from a 2-nodes kube cluster 300*2 (omsagent, ds) + 150*2 (omsagent-prometeus, ds) + 300 (rs) = 1200mb of ram.

**Comment by ganga1980** [comment]
> @ganga1980 I wrote all info there - #624 As for now, it is reproduceable on any new empty cluster. 300mb of ram per omsagent instance + 150mb of ram per omsagent-prometeus instance. Which takes from a 2-nodes kube cluster 300x2 (omsagent, ds) + 150x2 (omsagent-prometeus, ds) + 300 (omsagent, rs) = 1200mb of ram.

> Thanks for the feedback @MasterKolka . We have work items to  investigate & optimize the overall memory usage and as part of this optimization, first thing, we are planning to push the release to turn off all the processes in omsagent-Prometheus sidecar container if there is no scrape config.  We can circle back as make progress on this, as its takes considerable time to bring down overall memory usage.

**Comment by EderRoger** [comment]
Hi @ganga1980 , my cluster infos is pretty similar. 
Thanks for sharing @MasterKolka and thanks for looking into this @ganga1980

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by ganga1980** [comment]
Hi, @MrImpossibru , As part of our next agent release, we are pushing the memory optimizations as described in this PR - https://github.com/microsoft/Docker-Provider/pull/769

**Comment by MrImpossibru** [comment]
@ganga1980 Cool. At least it will roll back the situation with memory consumption like it was last October.

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
up

**Comment by ganga1980** [comment]
Hi, @MrImpossibru , we already rolled out the optimizations which I mentioned earlier. That should have been rolled out to your clusters already.

**Comment by MrImpossibru** [comment]
@ganga1980 I'll check. If omsagent still uses 300mb per instance and replicaset exists in the cluster (nobody described it's purpose) I'll reopen this issue by creating another one.
This was an initial issue, Prometheus agent was added later and made it worse.
