### ISSUE TITLE
OMS agent does not exclude namespaces after configuration

### ISSUE THREAD

**Issue by VincentVerweij** [microsoft/Docker-Provider#804]
This is a duplicate of #737 in which I did post a comment (as no solution is mentioned in there) but got no answer yet.
Since it is a closed issue I don't think many people will look into it, so let me post a new issue.

I do have an AKS cluster setup with Container Insights enabled.
My log analytics workspace contains alot of logs that I don't use so I want to limit the collected logs.

I did create the ConfigMap based on [this template](https://aka.ms/container-azm-ms-agentconfig) in the kube-system which is deployed to my cluster.
When calling `kubectl edit configmap container-azm-ms-agentconfig -n kube-system` I get the following:
![Screenshot ConfigMap edit](https://i.stack.imgur.com/601jb.png)

I do have a 3 separate namespaces: `kube-system`, `grafana-namespace` and `apps-namespace`.
I only want to capture the last one's logs.

While checking one of the `omsagent-...` pods' logs, I get the following:
```
Both stdout & stderr log collection are turned off for namespaces: '*.csv2,*_kube-system_*.log,*_grafana-namespace_*.log'
****************End Config Processing********************
****************Start Config Processing********************
config::configmap container-azm-ms-agentconfig for agent settings mounted, parsing values
config::Successfully parsed mounted config map
```
So the configuration itself has no errors in there, and is applied properly.

Now when I check the Log analytics workspace, I still get data in there that is referring to `kube-system` and `grafana-namespace`.
So, for example this query returns results for the last 5 minutes while the ConfigMap is already deployed for a week or so:
```
KubePodInventory
| where Namespace == "kube-system"
```

When reading [the Microsoft docs](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config) the ConfigMap should reduce the ingestion of logs if you exclude a namespace.

The main question is, what did I do wrong in the configuration or I am wrong in thinking that `KubePodInventory` shouldn't contain any data for the excluded namespaces.

**Comment by vishiy** [comment]
Those config map settings apply only for stdout and/or stderr container logs (and hence only ContainerLog table items) , as the configmap setting grouping name says.

**Comment by VincentVerweij** [comment]
@vishiy thank you for your answer. Ok, did not know that. Thought that tables like `KubePodInventory` was related so that it would not capture that as well.

Question is then, is there a way to reduce those captures?

**Comment by ganga1980** [comment]
Hi, @VincentVerweij , We are working on adding support for  namespace filtering for  inventory and perf metrics tables and will update you as soon this feature available.

**Comment by EvertonSA** [comment]
is this implemented?
