### ISSUE TITLE
How to configure the secured endpoint for metric collection

### ISSUE THREAD

**Issue by songleo** [microsoft/Docker-Provider#830]
From this doc: https://github.com/microsoft/Docker-Provider/blob/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml#L70

we can configure the endpoint, then the agent can collect the metrics from my endpoint. but my endpoint is secured. something like this:

```
curl -u admin:password http://automation-controller-service.ansible-automation-platform:8080/api/v2/metrics
```

need to use the username and password to access it. I can not find any configuration to do it. do you know how to provide the auth info for my endpoint? thanks

**Comment by ganga1980** [comment]
Hi, @jameswnl , we don't have support for this in container insights logs agent i.e. monitoring addon.

**Comment by vdiec** [comment]
We are discussing the metrics addon over email so I will close this issue.

**Comment by ganga1980** [comment]
closing as per request from @vdiec
