### ISSUE TITLE
collect_all_kube_events is not working correctly

### ISSUE THREAD

**Issue by alex-matei** [microsoft/Docker-Provider#831]
Collecting all kube events is not working correctly, only the first 4000 events are recorded taking normal events into account. The loop for fetching events is missing the logic when collect_all_kube_events is enabled:

The code at this line: https://github.com/microsoft/Docker-Provider/blob/ci_prod/source/plugins/ruby/in_kube_events.rb#L115 should look like:

```
if @collectAllKubeEvents
            continuationToken, eventList = KubernetesApiClient.getResourcesAndContinuationToken("events?limit=#{@EVENTS_CHUNK_SIZE}&continue=#{continuationToken}")
          else
            continuationToken, eventList = KubernetesApiClient.getResourcesAndContinuationToken("events?fieldSelector=type!=Normal&limit=#{@EVENTS_CHUNK_SIZE}&continue=#{continuationToken}")
          end
```

**Comment by ganga1980** [comment]
Thanks, @alex-matei for reporting this issue. We will address this issue in our upcoming agent release.

**Comment by ganga1980** [comment]
@alex-matei , fixed this issue and
This fix will get rollout with our September agent release which we will be working on soon

**Comment by alex-matei** [comment]
@ganga1980 Thanks for fixing it.
