### ISSUE TITLE
Run fluentd with /etc/config/kube.conf

### ISSUE THREAD

**Issue by adrianabasoc-uipath** [microsoft/Docker-Provider#839]
When fluentd is run it uses the `/etc/fluent/kube.conf`: https://github.com/microsoft/Docker-Provider/blob/a697f5a9384a6ae30ddc7599487543eca6e2cfdc/kubernetes/linux/main.sh#L769
Shouldn't it use the `/etc/config/kube.conf` instead?

**Comment by ganga1980** [comment]
Hi, @adrianabasoc-uipath , No, the kube.conf path which being referenced/used is correct. We are not using the default fluentd config rather we are using our custom kube.conf file. https://github.com/microsoft/Docker-Provider/blob/ci_prod/build/linux/installer/conf/kube.conf which copied to /etc/fluent directory as part of the build step - https://github.com/microsoft/Docker-Provider/blob/ci_prod/build/linux/installer/datafiles/base_container.data#L118

**Comment by adrianabasoc-uipath** [comment]
But what is the purpose of the `kube.conf` from https://github.com/microsoft/Docker-Provider/blob/ci_prod/charts/azuremonitor-containers/templates/ama-logs-rs-configmap.yaml#L5 then? Shouldn't that be used to run fluentd so that the log collection can be easily modified through the ConfigMap, rather than using a predefined configuration?

**Comment by ganga1980** [comment]
> Hi @ganga1980, thanks for your quick response! I am still wondering what is the purpose of the `kube.conf` from https://github.com/microsoft/Docker-Provider/blob/ci_prod/charts/azuremonitor-containers/templates/ama-logs-rs-configmap.yaml#L5 then. Shouldn't that be used to run fluentd so that the log collection can be easily modified through the ConfigMap, rather than using a predefined configuration?

> @adrianabasoc-uipath , Modifying the kube.conf will break the curated Portal experience and recommended alerts. So because of this reason, kube.conf is not exposed rather the configuration exposed as part of the monitoring addon enablement or post enablement so that all the experience will infer the what settings applied and render the experience accordinly.
