### ISSUE TITLE
Prometheus logs not showing up in Log Analytics Workspace

### ISSUE THREAD

**Issue by VincentVerweij** [microsoft/Docker-Provider#850]
My pods has the following annotations for a few weeks:
- prometheus.io/path: /metrics
- prometheus.io/port: '8900'
- prometheus.io/scrape: 'true'

I have deployed a ConfigMap with the following settings, also a few weeks ago:
```
  prometheus-data-collection-settings: |-
    [prometheus_data_collection_settings.cluster]
        interval = "1m"
        fieldpass = ["mendix_concurrent_user_sessions", "mendix_connection_bus", "mendix_current_request_duration_seconds_bucket", "mendix_current_request_duration_seconds_count", "mendix_current_request_duration_seconds_sum", "mendix_jvm_memory_bytes", "mendix_jvm_memory_pool_bytes", "mendix_license_count", "mendix_named_users", "mendix_runtime_requests_total", "mendix_threadpool_handling_external_requests"]
        monitor_kubernetes_pods = true
        monitor_kubernetes_pods_namespaces = ["dev-apps"]

    [prometheus_data_collection_settings.node]
        interval = "1m"
```

[This Microsoft Learn article](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-prometheus?tabs=pod#query-prometheus-metrics-data) tells me where I need to look for querying Prometheus log, which in turn points me to [this article](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-log-query#prometheus-metrics).

When I write my query in the Log Analytics Workspace e.g.:
```
InsightsMetrics
| where Namespace contains "prometheus"
| summarize by Name
```
I only get the following results
- volume_manager_total_volumes
- kubelet_runtime_operations_total
- process_cpu_seconds_total
- process_resident_memory_bytes
- kubelet_running_pods

So, where are the other metrics that can be seen in my ConfigMap's fieldpass property? Am I missing something?

**Comment by ganga1980** [comment]
Hi, @VincentVerweij , Did you verify with curl, the pods  in dev-apps namespace emitting the metrics on port:8900?  If not, can you please check it and see if this issue with app (likely).

**Comment by ganga1980** [comment]
Hi, @VincentVerweij ,  can you please confirm these pods running inside the namespace - "dev-apps"  and also has the pod annotations? can you please share the output so that I can check if everything looks good?

**Comment by vdiec** [comment]
Hi @VincentVerweij, did you face any issues with the documentation? Please let me know so we can update it

**Comment by ganga1980** [comment]
> @ganga1980 It is most certainly running in that namespace, otherwise I would not have configured the namespace in the ConfigMap. It also has these annotations, as was documented and noted by you that I should have these on the pod.
> 
> Here is a `kubectl describe` of the pod that returned the metrics that I queried with cURL in my previous comment:
> 
> ```
> Name:         my-app-master-123456789-01234
> Namespace:    dev-apps
> Priority:     0
> Node:         aks-devapps-12100402-vmss00001q/10.33.0.53
> Start Time:   Mon, 28 Nov 2022 00:05:48 +0000
> Labels:       pod-template-hash=9756dd647
>               privatecloud.mendix.com/app=my-app
>               privatecloud.mendix.com/component=mendix-app
>               privatecloud.mendix.com/node-type=master
> Annotations:  buildGeneration: 32
>               configHash: <obfuscated_hash>
>               prometheus.io/path: /metrics
>               prometheus.io/port: 8900
>               prometheus.io/scrape: true
> Status:       Running
> IP:           10.33.0.45
> IPs:
>   IP:           10.33.0.45
> Controlled By:  ReplicaSet/my-app-master-123456789
> Containers:
>   mendix:
>     Container ID:   containerd://<obfuscated_hash>
>     Image:          obfuscated-customer-acr.azurecr.io/obfuscated-customer-acr:my-app
>     Image ID:       obfuscated-customer-acr.azurecr.io/obfuscated-customer-acr@sha256:<obfuscated_hash>
>     Port:           8080/TCP
>     Host Port:      0/TCP
>     State:          Running
>       Started:      Wed, 30 Nov 2022 06:39:06 +0000
>     Last State:     Terminated
>       Reason:       Completed
>       Exit Code:    0
>       Started:      Wed, 30 Nov 2022 03:35:59 +0000
>       Finished:     Wed, 30 Nov 2022 06:39:04 +0000
>     Ready:          True
>     Restart Count:  20
>     Limits:
>       cpu:     2
>       memory:  2000Mi
>     Requests:
>       cpu:      1
>       memory:   1000Mi
>     Liveness:   http-get http://:mendix-app/ delay=60s timeout=1s period=15s #success=1 #failure=3
>     Readiness:  http-get http://:mendix-app/ delay=5s timeout=1s period=1s #success=1 #failure=3
>     Environment:
>       M2EE_ADMIN_LISTEN_ADDRESSES:  127.0.0.1
>       M2EE_ADMIN_PORT:              9000
>       M2EE_ADMIN_PASS:              <set to the key 'adminpassword' in secret 'my-app-m2ee'>  Optional: false
>     Mounts:                         <none>
>   m2ee-sidecar:
>     Container ID:   containerd://<obfuscated_hash>
>     Image:          private-cloud.registry.mendix.com/mx-m2ee-sidecar:2.1.0
>     Image ID:       private-cloud.registry.mendix.com/mx-m2ee-sidecar@sha256:<obfuscated_hash>
>     Port:           8800/TCP
>     Host Port:      0/TCP
>     State:          Running
>       Started:      Mon, 28 Nov 2022 00:07:36 +0000
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       cpu:     250m
>       memory:  32Mi
>     Requests:
>       cpu:     100m
>       memory:  16Mi
>     Environment:
>       MX_NODE_TYPE:  master
>     Mounts:
>       /opt/mendix/config from runtime-config (ro)
>       /opt/mendix/m2ee from m2ee-config (ro)
>       /opt/mendix/services from services (ro)
>   m2ee-metrics:
>     Container ID:  containerd://<obfuscated_hash>
>     Image:         private-cloud.registry.mendix.com/mx-m2ee-metrics:2.1.0
>     Image ID:      private-cloud.registry.mendix.com/mx-m2ee-metrics@sha256:<obfuscated_hash>
>     Port:          8900/TCP
>     Host Port:     0/TCP
>     Args:
>       -port=8900
>     State:          Running
>       Started:      Mon, 28 Nov 2022 00:07:39 +0000
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       cpu:     250m
>       memory:  32Mi
>     Requests:
>       cpu:     100m
>       memory:  16Mi
>     Environment:
>       MX_APP_ID:  my-app
>     Mounts:
>       /opt/mendix/m2ee from m2ee-config (ro)
> Conditions:
>   Type              Status
>   Initialized       True 
>   Ready             True 
>   ContainersReady   True 
>   PodScheduled      True 
> Volumes:
>   m2ee-config:
>     Type:                Projected (a volume that contains injected data from multiple sources)
>     SecretName:          my-app-m2ee
>     SecretOptionalName:  <nil>
>   runtime-config:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      my-app-runtime-config
>     Optional:  false
>   services:
>     Type:                Projected (a volume that contains injected data from multiple sources)
>     SecretName:          my-app-database
>     SecretOptionalName:  <nil>
>     SecretName:          my-app-file
>     SecretOptionalName:  <nil>
> QoS Class:               Burstable
> Node-Selectors:          <none>
> Tolerations:             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
>                          node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>                          node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> Events:                  <none>
> ```
> 
> @vdiec currently no issues with the documentation, just that I don't see anything of Prometheus in my log analytics workspace. When something is unclear, I will notify you about it 😄
 @VincentVerweij ,  can you please check the telegraf process running in all the pods (in both ama-logs & ama-logs-prometheus container) through "ps aux" command ? if its test cluster, can you please share the AKS cluster name or AKS cluster resource id to investigate what cause prometheus metrics not getting ingested? or can you please create support ticket to get this investigated and provide the resolution to this issue?
