### ISSUE TITLE
can we add new feature for container insight to collect log for specific pod

### ISSUE THREAD

**Issue by tfbubu111** [microsoft/Docker-Provider#867]
-by default container insight won't collect logs for kube-system namespace, but sometimes we need to check kube-system pod log for further troubleshooting, such as coreDNS

-many users have concern to enable the whole namespace log collection(kube-system), cause log capacity maybe huge and needs lots of expense 

-can we enable log collection for specific pod in kube-system

**Comment by ganga1980** [comment]
@tfbubu111 , thanks for raising this request and its valid user scenario. Sure, will add this ask to our backlog. @austonli , lets track this ask as part of cost optimization feature.
