### ISSUE TITLE
Control ingestion of Perf logs

### ISSUE THREAD

**Issue by gunnim** [microsoft/Docker-Provider#882]
I've been reading through https://techcommunity.microsoft.com/t5/fasttrack-for-azure/aks-container-insights-logging-level-and-associated-costs/ba-p/3684224 and the Container Insights documentation looking to limit our Perf logs ingestion.

In our case, the Prometheus option would not amount to cost-savings since we need dashboards and as I understand it, the Container Insights views do not read from Prometheus ingested logs. Therefore we would be going the Grafana route and managed Grafana in Azure has some cost to it.

"Azure Monitor Container Insights DCR" looks like the route for us, however the signup page says preview should have ended by now but I can't find any further documentation or information on the web about it.

Is it available today ?

Do I have other options available to f.x. control the polling rate for the Perf metrics ?

**Comment by ganga1980** [comment]
Hi, @gunnim, We are working on rolling out the cost optimization feature which would enable to specify collection frequency and namespaces to include or exclude.  Tennantite ETA for this feature to be available end of Jan or early Feb.

**Comment by vdiec** [comment]
Hi @gunnim , this is available now. Learn more here https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-cost-config?tabs=create-CLI
