### ISSUE TITLE
Update Recommended Alerts

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/Docker-Provider#920]
The [Recommended Alerts](https://github.com/microsoft/Docker-Provider/tree/ci_dev/alerts/recommended_alerts_ARM) are slightly out of date:
* They're missing the `criterionType` introduced by dynamic metric alerts.
* The recommended alerts deployed through the portal don't totally match the similarly named alerts in this repo. Here's a what-if deployment of the NodeWorkingSetMemoryPercentage.json:
  ```shell
         + skipMetricValidation: true
        ~ metricName:           "node_memory_working_set_percentage" => "memoryWorkingSetPercentage"
        ~ metricNamespace:      "Microsoft.ContainerService/managedClusters" => "Insights.Container/nodes"
        ~ name:                 "Metric1" => "1st criterion"
      properties.criteria.odata.type: "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria" => "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"
  ```
* They're not bicep templates

**Comment by ganga1980** [comment]
Hi, @carlin-q-scott  - Container Insights supports recommended alerts based on Prometheus metrics and recommended alerts based on the metrics rules are in deprecation path so trying upgrading to Prometheus metrics based recommended alerts. Here is the doc link - https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-metric-alerts?tabs=azure-portal
